socket.o: socket.c socket.h configuration.h
client.o: client.c configuration.h socket.h tools.h http.h client.h
tools.o: tools.c tools.h configuration.h socket.h
main.o: main.c configuration.h socket.h fileReader.h client.h http.h
fileReader.o: fileReader.c configuration.h socket.h fileReader.h
